#!/bin/bash -e

export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

export BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export IMG_NAME='BarnacleOS'
export USERNAME='user'
export PASSWORD='password'

export DEPLOY_DIR="$BASE_DIR/deploy"
export ROOTFS_DIR="$BASE_DIR/rootfs"
export KEYS_DIR="$BASE_DIR/keys"
export FILES_DIR="$BASE_DIR/files"

export IMG_DATE="$(date +%Y-%m-%d)"

export IMG_FILE="$DEPLOY_DIR/$IMG_NAME-${IMG_DATE}.img"

cd "$BASE_DIR"

mkdir -p "$DEPLOY_DIR"

exec bash -e $@
